---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    app: {{ template "name" . }}