replicaCount: 1

image:
  repository: data-loader-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx

app:
  port: 2000
  juliaThreads: 4

resources:
  limits:
    cpu: 4000m
    memory: 32768Mi
  requests:
    cpu: 1000m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

optimalReality:
  logLevel: INFO

postgresql:
  database: or_dot
  endpoint: artc-dev.ckoda85kvzl3.ap-southeast-2.rds.amazonaws.com:5432
  password: postgres
  username: oradmin

postgresqlSimulation:
  database: ordb
  endpoint: artc-dev.ckoda85kvzl3.ap-southeast-2.rds.amazonaws.com:5432
  password: postgres
  username: postgres

redis:
  endpoint: redis:6379

tile38:
  endpoint: tile38:9851

tpoc:
  aws_access_key_id:
  aws_secret_access_key:
  aws_region: 
  aws_s3_bucket: or-dot-poc-data


experimentManager:
  masterJWT: