apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphql-service.fullname" . }}
  labels:
  {{- include "graphql-service.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql_password: {{ .Values.postgresql.password | b64enc | quote }}
  postgresql_username: {{ .Values.postgresql.username | b64enc | quote }}