apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphql-service.name" . }}
  labels:
    {{- include "graphql-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5100
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "graphql-service.selectorLabels" . | nindent 4 }}
