apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-loader-service.fullname" . }}
  labels:
    {{- include "data-loader-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "data-loader-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "data-loader-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "data-loader-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: EXPERIMENT_MANAGER_ENDPOINT
            value: http://graphql-service.{{ .Release.Namespace }}
          - name: EXPERIMENT_MANAGER_WS_ENDPOINT
            value: ws://graphql-service.{{ .Release.Namespace }}
          - name: APP_PORT
            value: {{ .Values.app.port | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.optimalReality.logLevel }}
          - name: CERT_FILE
            value: localhost.pem
          - name: CERT_KEY_FILE
            value: localhost-key.pem
          - name: PG_ENDPOINT
            value: {{ .Values.postgresql.endpoint }}
          - name: PG_DBNAME
            value: {{ .Values.postgresql.database }}
          - name: PG_USER
            value: {{ .Values.postgresql.username }}
          - name: PG_PASSWORD
            value: {{ .Values.postgresql.password }}
          - name: PG_SIM_ENDPOINT
            value: {{ .Values.postgresqlSimulation.endpoint }}
          - name: PG_SIM_DBNAME
            value: {{ .Values.postgresqlSimulation.database }}
          - name: PG_SIM_USER
            value: {{ .Values.postgresqlSimulation.username }}
          - name: PG_SIM_PASSWORD
            value: {{ .Values.postgresqlSimulation.password }}
          - name: REDIS_ENDPOINT
            value: {{ .Values.redis.endpoint }}
          - name: TILE38_ENDPOINT
            value: {{ .Values.tile38.endpoint }}
          - name: OR_MASTER_JWT
            value: {{ .Values.experimentManager.masterJWT }}
          - name: JULIA_NUM_THREADS
            value: {{ .Values.app.juliaThreads | quote }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.tpoc.aws_access_key_id }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .Values.tpoc.aws_secret_access_key }}
          - name: AWS_REGION
            value: {{ .Values.tpoc.aws_region }}
          - name: AWS_S3_BUCKET
            value: {{ .Values.tpoc.aws_s3_bucket }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.app.port }}
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.app.port }}
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
